version: "3.8"
services:
  mutt-db:
    image: "postgres:13.0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    container_name: "mutt-db"
    healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DATABASE"]
            timeout: 20s
            retries: 10
  create-db:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    container_name: "create-db"
    environment:
      - DB_HOST=mutt-db
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - PGPASSWORD=postgres
    depends_on:
      mutt-db:
        condition: service_healthy

networks:
  default:
    external:
      name: mutt-network